"""Add unique constraint on subscription stripe_subscription_id

Revision ID: aaa632c2d13d
Revises: b82e4142b242
Create Date: 2026-05-26 04:21:14.452263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa632c2d13d'
down_revision: Union[str, Sequence[str], None] = 'b82e4142b242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subscriptions_stripe_subscription_id', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subscriptions_stripe_subscription_id', type_='unique')
    # ### end Alembic commands ###
